### ISSUE TITLE
Type 'WebStream<string>' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by thapecroth** [openpgpjs/openpgpjs#1546]
Got the following error when running 

`tsc --noEmit
`
```
node_modules/openpgp/openpgp.d.ts:10:85 - error TS2307: Cannot find module '@openpgp/web-stream-tools' or its corresponding type declarations.

10 import type { WebStream as GenericWebStream, NodeStream as GenericNodeStream } from '@openpgp/web-stream-tools';
                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/utils/utils.ts:11:3 - error TS2322: Type 'WebStream<string>' is not assignable to type 'string'.
```
On openpgp version 5.3.0

I believe this is cause by the fact that in the package.json, it listed as devdependency instead of dependency !?

**Comment by thapecroth** [comment]
Turn out I can just fixed it by install opengpp 5.3.1.

**Comment by srn271** [comment]
I get the same error when upgrading from 5.10 to >=5.2.0 && <= 5.5.0.

The error is probably due to the changes in this commit:
https://github.com/openpgpjs/openpgpjs/commit/d89cc48bf33f7f9b9bff9f87e0da0f04724d700c

```ts
const encrypted: string = await openpgp.encrypt({
  message, // openpgp.Message<string>
  encryptionKeys, // openpgp.PublicKey[]
  signingKeys // openpgp.PrivateKey[]
})
```

**Comment by srn271** [comment]
Nevermind. Installing the latest version of `@openpgp/web-stream-tools` (0.0.11) fixes the issue.

_Should be mentioned in the documentation or even in the release notes, as already addressed in_ https://github.com/openpgpjs/openpgpjs/pull/1502#issuecomment-1241947723.

**Comment by rene-leanix** [comment]
Having to install an additional package like `@openpgp/web-stream-tools` to fix the typing isn't a great solution, of course, but it also doesn't seem to work any more either.

The reason it doesn't work is that `@openpgp/web-stream-tools` does not export the interface `NodeStream` (any more?), which is why TypeScript treats it as `any`, with the result that the conditional `T extends NodeStream<infer X>` is always evaluated as true, so the resulting type is `NodeStream<string>`, even if `T` is string. In other words, the return type of `openpgp.encrypt<string>()` is `Promise<NodeStream<string>>` and not `Promise<string>`.

This can be fixed by changing

```ts
export function encrypt<T extends MaybeStream<Data>>(options: EncryptOptions & { message: Message<T>, format?: 'armored' }): Promise<
  T extends WebStream<infer X> ? WebStream<string> :
  T extends NodeStream<infer X> ? NodeStream<string> :
  string
>;
```

to

```ts
export function encrypt<T extends MaybeStream<Data>>(options: EncryptOptions & { message: Message<T>, format?: 'armored' }): Promise<
  T extends ReadableStream<unknown> ? (
    T extends WebStream<unknown> ? WebStream<string> :
    T extends NodeStream<unknown> ? NodeStream<string> :
    string
  ) : string
>;
```

As this check is done in several places, it may be good to define a new generic type of it, e.g.:

```ts
type StreamOrSimple<MessageType, SimpleReturnType> = MessageType extends ReadableStream<unknown> ? (
  MessageType extends WebStream<unknown> ? WebStream<SimpleReturnType> :
  MessageType extends NodeStream<unknown> ? NodeStream<SimpleReturnType> :
  SimpleReturnType
) : SimpleReturnType;

export function encrypt<T extends MaybeStream<Data>>(options: EncryptOptions & { message: Message<T>, format?: 'armored' }): Promise<StreamOrSimple<T, string>>;
export function encrypt<T extends MaybeStream<Data>>(options: EncryptOptions & { message: Message<T>, format: 'binary' }): Promise<StreamOrSimple<T, Uint8Array>>;
export function encrypt<T extends MaybeStream<Data>>(options: EncryptOptions & { message: Message<T>, format: 'object' }): Promise<Message<T>>;
```

Should I create a PR along those lines, @larabr?

**Comment by larabr** [comment]
@rene-leanix please see if the issue is resolved with this fix: https://github.com/openpgpjs/openpgpjs/issues/1720#issuecomment-1923586318

**Comment by rene-leanix** [comment]
@larabr, yes, installing `@openpgp/web-stream-tools@0.0.11-patch-0` also fixes the issue, as it still contains a definition of `NodeStream`. Thanks! I missed that issue.

It should still be preferable to adjust the typing to avoid the need to install `@openpgp/web-stream-tools`.
