### ISSUE TITLE
Questions on current build process

### ISSUE THREAD

**Issue by tanx** [openpgpjs/openpgpjs#387]
So I've started work on https://github.com/openpgpjs/openpgpjs/issues/385 on the [es6 branch](https://github.com/openpgpjs/openpgpjs/compare/es6) but unfortunately I'm having some questions about the current build.

* I get this error message when calling `grunt` after a clean checkout of the master branch:

````
Running "browserify:unittests" (browserify) task
>> Bundle test/openpgp.js created.
>> Error: Cannot find module 'openpgp' from '/Users/tanx/Projects/openpgpjs/test/general'
Warning: Error running grunt-browserify. Use --force to continue.
````

* Why are we building `test/openpgp.js` [here](
https://github.com/openpgpjs/openpgpjs/blob/79034f8ddeecf5d1ad4fe0193d22e2b95b5c879e/Gruntfile.js#L48)?

* Why are we copying the complete contents of `src/` to `test/` [here](https://github.com/openpgpjs/openpgpjs/blob/79034f8ddeecf5d1ad4fe0193d22e2b95b5c879e/Gruntfile.js#L154-L160)?

Thanks for clarifying!

**Comment by evilaliv3** [comment]
hello there @tanx ! cool to see you are giving some love to openpgpjs :)

i'm not remembering exactly (and i will be back to you tonight with a precise answer ) but both the two things have been introduced in order to copy sources in the test directory in order to be able to instruct them with istambul and track code coverage.

**Comment by evilaliv3** [comment]
ok just reviewed;

it seems that both are not needed anymore; i think that was something i needed in the first step when i was implementing this and then probably i forgotten to remove them.

i'm pushing a new branch called "coverage-retesting" where to see that all is able to work without issues removing both all the code you highligthed.

**Comment by evilaliv3** [comment]
yep i confirm those lines are totally unneded: https://travis-ci.org/openpgpjs/openpgpjs/jobs/103898393

i'm merging their removal on the master branch @tanx; you can rebase your branch on it!

**Comment by evilaliv3** [comment]
the merged patch is the following: https://github.com/openpgpjs/openpgpjs/commit/b92efd6087c7f5bff855a4d60e0f7df4b9620661

**Comment by tanx** [comment]
Awesome! Thanks for the quick response. I rebased the es6 branch on top of the current master.

I'm still having the following problem though. I'm not sure what I'm doing wrong since the grunt build works fine on travis for node v0.12 and v4.2 (I'm using v4.2 on my machine to build locally). Any ideas?

> I get this error message when calling `grunt` after a clean checkout of the master branch:

````
Running "browserify:unittests" (browserify) task
>> Bundle test/openpgp.js created.
>> Error: Cannot find module 'openpgp' from '/Users/tanx/Projects/openpgpjs/test/general'
Warning: Error running grunt-browserify. Use --force to continue.
````

**Comment by evilaliv3** [comment]
ah right, you have what are the commands you do for doing the build @tanx?

maybe you are not building it all:
```
  grunt.registerTask('test', ['copy:npm', 'mochaTest']);
  grunt.registerTask('coverage', ['default', 'copy:npm', 'mocha_istanbul:coverage']);
  grunt.registerTask('coveralls', ['default', 'copy:npm', 'mocha_istanbul:coveralls']);
  grunt.registerTask('saucelabs', ['default', 'copy:npm', 'connect', 'saucelabs-mocha']);
```

these are the current possibilities:

```grunt && grunt test``` (this does default + test)
or one of the ```grunt coverage```, ```grunt coveralls``` or ```grunt saucelabs``` that include already grunt default.

**Comment by tanx** [comment]
Mmmh. I'm pretty sure I'm not doing anything wrong. But the travis builds work fine. My guess is that it's a problem with my local installation of npm. I've been reading about other users having similar issues of modules not being found [here](http://stackoverflow.com/questions/12594541/npm-global-install-cannot-find-module). Word on the street is to whipe the global `node_modules` folder, wipe the npm cache, and reinstall node+npm. I'll try that once I'm out of the jungle and have a decent internet connect ;)

Closing this issue for now. Thanks for your help though :)

**Comment by evilaliv3** [comment]
Reopening the issue as i finally managed to reproduce your issue with a clean setup:

```bash
git clone git@github.com:openpgpjs/openpgpjs.git
cd openpgpjs
npm install -d
grunt && grunt test
```

i now re-launched a travis build having cleaned the travis npm cache that maybe was hiding the bug and i'm waiting for the output of the commands executed by travis to see what we are forgetting to do while retesting manually.

**Comment by evilaliv3** [comment]
Ok, confirmed that now that the travis cache is empty the package is failing to build; so the bug is probably hidden in a recent dependency update.

Given this first step is to disable the travis cache in general as it may hide this kind of bugs for the future; sorry travisCI for the overhead but... !

**Comment by tanx** [comment]
Nice! I was beginning to question my sanity as the issue basically cost me all day :)

It's good that we can reproduce these issue on travis. So +1 on deactivating the npm cache.

Do you think the issue is because of node/npm or are those not cached on travis? It would help me to narrow down the responsible dependency update.

Also: we might want to consider using `npm shrinkwrap` to prevent these issue and keep our dependency tree stable at least until we manually update them with a working good build locally. Details here:

https://docs.npmjs.com/cli/shrinkwrap

**Comment by evilaliv3** [comment]
@tanx: i've just retested you pull request https://github.com/openpgpjs/openpgpjs/pull/388 and it is solving the issue :)

the fact that on travis the cache was making it work is due to the fact that the cached node_modules directory was caching an old working state.

I've never used ```npm shrinkwrap``` but its seems useful; i genarally do the same on GlobaLeaks while dealing with pip dependencies with ```pip freeze``` in order to be sure to fix no only the version of the direct dependencies but also the dependencies of the dependencies.

Let's open a specific ticket for dealing with this.

**Comment by evilaliv3** [comment]
Damn!

Your pull @tanx is able to make ```grunt``` work without stating that it is not able to find npm.

What now is failing is the subsequent ```grunt mochaTest:unittests```:

```bash
evilaliv3@remotehost:~/test/openpgpjs$ grunt 
Running "default" task
>> Before Submitting a Pull Request please also run `grunt jshint`.

Running "clean:0" (clean) task
>> 1 path cleaned.

Running "copy:zlib" (copy) task
Copied 3 files

Running "browserify:openpgp" (browserify) task
>> Bundle dist/openpgp.js created.

Running "browserify:openpgp_debug" (browserify) task
>> Bundle dist/openpgp_debug.js created.

Running "browserify:worker" (browserify) task
>> Bundle dist/openpgp.worker.js created.

Running "browserify:worker_min" (browserify) task
>> Bundle dist/openpgp.worker.min.js created.

Running "browserify:unittests" (browserify) task
>> Bundle test/lib/unittests-bundle.js created.

Running "replace:openpgp" (replace) task

Running "replace:openpgp_debug" (replace) task

Running "replace:worker_min" (replace) task

Running "uglify:openpgp" (uglify) task
>> 2 files created.

Done, without errors.
evilaliv3@remotehost:~/test/openpgpjs$ grunt test
Running "copy:npm" (copy) task
Copied 4 files

Running "mochaTest:unittests" (mochaTest) task
>> Mocha exploded!
>> Error: Cannot find module 'openpgp'
>>     at Function.Module._resolveFilename (module.js:337:15)
>>     at Function.Module._load (module.js:287:25)
>>     at Module.require (module.js:366:17)
>>     at require (module.js:385:17)
>>     at Object.<anonymous> (/home/evilaliv3/test/openpgpjs/test/general/basic.js:3:81)
>>     at Module._compile (module.js:435:26)
>>     at Object.Module._extensions..js (module.js:442:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:311:12)
>>     at Module.require (module.js:366:17)
>>     at require (module.js:385:17)
Warning: Task "mochaTest:unittests" failed. Use --force to continue.
```

**Comment by tanx** [comment]
Yep. Same error on my machine. Mochatest can't find 'openpgp'.

**Comment by tanx** [comment]
I think you updated the npm dependencies in the package.json recently. The npm cache on travis probably hid the error until I did a clean checkout of the repo a few days and noticed it. I remember choosing the old versions of certain dependencies specifically because they caused problems like this. Perhaps if we try to go through the npm depencies by comparing the npm cache with current dependency tree?

**Comment by evilaliv3** [comment]
I'm quite sure the issue exists from this https://github.com/openpgpjs/openpgpjs/commit/b526d16aebc9ec89d6f394bb7f13c3a40de16117 and specifically only in relation to the browserify update.

Anyway i've seen also some bugs in the Gruntfile (both in the master and in your pull request);
I'm finishing a call and i then i will be onto it.

**Comment by evilaliv3** [comment]
@tanx: i'm iterating on fixing on https://github.com/openpgpjs/openpgpjs/tree/fix/387 integrating all your patches and fixing the following two problems:

1) since https://github.com/openpgpjs/openpgpjs/commit/d3576b6e, npm_pack was installing openpgp in the local node_modules/openpgp and this is currently the directories from which the require('openpgp') inside unit tests try to load openpgp; why npm_pack was needed? were you awere that the tests were finding the package there? i'm evaluating how to make it loads the build openpgp.js, but maybe you already know how to do it

2) the other issue are related to the new browserify; i#m giving a try to use it and if not i will revert it.

**Comment by evilaliv3** [comment]
i think by the way that currently there is really a lot of confusion in how tests are implemented right now given that they still do something that was probably needed at the time of phantomjs

browserify is needed only for the build the dist/openpgp.js for production or to run browsertesting, but mocha not need it when we run "grunt test" so that we can try to simply revert what @toberndo did in https://github.com/openpgpjs/openpgpjs/commit/a4598f3b; this way all tests except the one run in the browser will test the sources.
is since that commit + the later https://github.com/openpgpjs/openpgpjs/commit/d3576b6e that during testing openpgp is loaded from node_modules/openpgpjs

i'm now retesting the revert of both and i will give you feedback when done

**Comment by tanx** [comment]
I think the issue has nothing to do with browserify. In fact it can be reproduced without a browserify build on the master branch. Here's why:

* Grunt mochaTest is sole a node test runner. It does not depend on a browserify build. It looks for the `'openpgp'` module which is provided locally by the project's own package.json file, which in turn points to `src/index.js`. This can be reproduced on the master branch like so:

````
grunt clean #wipe dist/
grunt mochaTest #run mocha tests directly under node
````
    
* The grunt mochaTest job just happens to run after the browserify:unittests grunt job (which was wrongly configured and was fixed in https://github.com/openpgpjs/openpgpjs/commit/274a44e5161429a6c77660a905199b8596b2d0d7). This was causing browserify to wrongly include the whole openpgp.js src tree in the unittests.js bundle that was used by phantom.js and is still used in testing locally in the browser.

* The reason this bug has been overshadowed in travis ci is because of our caching of node_modules which was fixed in https://github.com/openpgpjs/openpgpjs/commit/d784f5d59339920aeefafe3bca12e746a54b70a2. How can this be verified? Well the travis builds for the cleanup-build branch:

This one worked: https://travis-ci.org/openpgpjs/openpgpjs/builds/104039281
This one failed: https://travis-ci.org/openpgpjs/openpgpjs/builds/104129677

==> I'm pretty sure the issue is caused by a transative dependency update somewhere in our node_modules tree. We just need to figure out the difference between the cached modules (in travis) and the locally installed modules.

**Comment by evilaliv3** [comment]
I let you focus on the following (that anyhow seems to be all solved in my updated pull request)

- openpgp.js was not found since we both started testing your removal of npm_pack; this was because npm_pack setups openpgp in node_modules/openpgp.js; you can checkout here https://github.com/openpgpjs/openpgpjs/commit/a730d3f7ad72cc1bfcdc9dbe91619a4ea4e3ab86 that is the commit before the updates of the dependencies and do ```npm install -d && grunt && grunt test``` an you will find openpgp in node_modules; delete it, rerun grunt test and you will see the error for the library missing.

- the reason why the travis cache was shadowing the error in the recent removal of npm_pack was the fact that the cache was still having openpgpjs in node_modules; that is the same reason i was not discovering the bug before today when i pointed you to the retesting commands on a clean git clone.

the issue in general by the way was caused by browserify not used correctly as you pointed but shadowed and complicated by the things i'm reporting;
the breaking commits by the way were:
- last working: https://github.com/openpgpjs/openpgpjs/commit/a730d3f7ad72cc1bfcdc9dbe91619a4ea4e3ab86
the breaking one with dependencies updates and the wrong browserifyOptions you spotted: https://github.com/openpgpjs/openpgpjs/commit/b526d16aebc9ec89d6f394bb7f13c3a40de16117

**Comment by tanx** [comment]
Finally closing this. Thanks so much for your help. I think we finally have a nice clean build again now 👍🏼

**Comment by tanx** [comment]
FYI I added `npm shrinkwrap` to `release.sh` in https://github.com/openpgpjs/openpgpjs/commit/8070120b45e145c992e1b9bec009b89e3abfa91b. So that the versions of dependencies stay consistent between versions of openpgp.js. I released v1.5.3 with a shrinkwrapped version. You can see an example [here](https://github.com/openpgpjs/openpgpjs/blob/master/npm-shrinkwrap.json).

**Comment by evilaliv3** [comment]
cool! well done; i'm now evaluating to do the same in GlobaLeaks :)

**Comment by evilaliv3** [comment]
@tanx i've seen that currently all the build on travis are failing with an error:

```Not compatible with your operating system or architecture: fsevents@1.0.6```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/105653118/log.txt

I think this could be related to: https://github.com/npm/npm/issues/8707
Which version of npm are you using for building that shrinkrap?

Given this failure, It seems in general that we should log the npm version accordingly in order to be able to be somehow reproducible in the build.

**Comment by tanx** [comment]
> @tanx i've seen that currently all the build on travis are failing with an error:
> 
> Not compatible with your operating system or architecture: fsevents@1.0.6
> 
> https://s3.amazonaws.com/archive.travis-ci.org/jobs/105653118/log.txt

Yeah I saw. This issue doesn't seem to be caused by shrinkwrap, since it happens for the commit https://github.com/openpgpjs/openpgpjs/commit/56ecc9e0cdbee061e6b433a9535d7457ff513a6c already. And I wasn't using shrinkwrap there yet:
https://travis-ci.org/openpgpjs/openpgpjs/jobs/105653118

> I think this could be related to: npm/npm#8707
> Which version of npm are you using for building that shrinkrap?

I'm using 3.5.3. According to the following that version should work fine:
https://github.com/npm/npm/issues/8707#issuecomment-143358012

> Given this failure, It seems in general that we should log the npm version accordingly in order to be able to be somehow reproducible in the build.

Let's see if this is caused by npm or another package first.

**Comment by tanx** [comment]
Using node v5.5 for the travis build seems to fix the issue:
https://travis-ci.org/openpgpjs/openpgpjs/builds/105718353

I'll open a PR once the builds are through. Seems like we should have shrinkwrapped a few days ago, since I can't reproduce the node_modules tree that worked for the old node versions. But if upgrading to 5.5 fixes the issue I would be fine with that as well.

**Comment by evilaliv3** [comment]
wait; :)

it's exactly commit https://github.com/openpgpjs/openpgpjs/commit/56ecc9e0cdbee061e6b433a9535d7457ff513a6c that adds the shrinkwrap json file so i confirm that it's shrinkwrap that is causing the issue.

i would suggest to give a try to the LTS and try to run make the shringwrap on that and put that on travis for retesting.

what do you think?

**Comment by tanx** [comment]
> it's exactly commit 56ecc9e that adds the shrinkwrap json file so i confirm that it's shrinkwrap that is causing the issue.

Oops. Sorry my mistake. You're right.

> i would suggest to give a try to the LTS and try to run make the shringwrap on that and put that on travis for retesting.
> 
> what do you think?

Ok. I upgrade to node v5.5 on my mac. But I guess since I'm the maintainer on npm I should release stuff that v0.12 and v4.2 users can install as well. So I guess I'll have to downgrade to LTS :(

I'll re-shrinkwrap and we'll see if it fixes things.

**Comment by evilaliv3** [comment]
i was exaclly goint to make you a question that is: are you using a mac? so i've got the solution!

**Comment by evilaliv3** [comment]
basically when one run ```npm shrinkwrap``` it fixes dependencies for the OS but this causes further ```npm install``` to work only on that OS.

e.g. i just run ```npm install``` on my Linux and i got the same error as in travis.

this makes clear two things:
- if we want to get this high reproducibility we should eventually release always build from the same OS
- the OS on which run shrinkwrap should be eventually only Linux as we have all tests runned against linux

**Comment by evilaliv3** [comment]
the alternative for the moment as by the following tickets are to remove fsevents from the generated shrinkwrap and move this only to ```optionalDependencies```

https://github.com/npm/npm/issues/2679
https://github.com/appium/appium/pull/6006

**Comment by tanx** [comment]
Good call: https://travis-ci.org/openpgpjs/openpgpjs/builds/105737354
